### ISSUE TITLE
ajax.php /  delete-file

### ISSUE THREAD

**Issue by ceballosm** [cyberperspectives/sagacity#1]
The 'filename' parameter can be abused by a directory traversal attack. 

`action=delete-file&filename=../../../windows/system32/test.txt

{"success":"Deleted file"}
`

**Comment by cyberperspectives** [comment]
Yep, sure can.  The tool was intended for localhost only access and there are warnings talking about that.  If you have a specific example of a case where the tool does delete files like that feel free to update and we'll look into it.

**Comment by ceballosm** [comment]
this attack can happen local. Using a browser's debug tools, an unpriv user can delete files that are not owned by them.

**Comment by godsgood33** [comment]
I couldn't make that happen, so please outline the steps to duplicate your outcome.

**Comment by ceballosm** [comment]
![1](https://user-images.githubusercontent.com/30805891/41065306-e4a2a5f4-69a3-11e8-8568-69ae7086b781.png)

![2](https://user-images.githubusercontent.com/30805891/41065334-f6a89b8c-69a3-11e8-9f56-111cd7052263.png)

anything else?

**Comment by godsgood33** [comment]
Ok, so you've posed two different problems...

1. Your original issue showed it deleting a file in Windows\System32.  I checked this first and couldn't do it.  I returns that the file "does not exist".  So at least on Windows 10, this is a non-issue (looks like you might be running Win 7 though).
2. You images show it deleting something from the root directory.  On Windows all users have full access to this directory because the way it is setup, if they didn't they wouldn't be able to do anything on the system.

Ultimately, this is a problem with Apache running as a SYSTEM account on Windows.  On Linux this is much harder to accomplish.

Also, you imply that the problem is using the "filename" parameter.  But changing that is not going to fix the issue.  Feel free to push a fix and we'll take a look at it.

And as stated, this is a niche product intended for local use only, and so that could be done a lot easier than "hacking" it and issuing a AJAX request.

**Comment by ceballosm** [comment]
1. Image showing a unpriv user attempting to delete a file outside of xampp.

![1](https://user-images.githubusercontent.com/30805891/41102880-6cb38356-6a57-11e8-995b-3681252ec3ce.png)

as you can see the file does exist. then it is not due to the issue in the following image.

2. Image of unpriv user deleting the file not controlled by them.

![2](https://user-images.githubusercontent.com/30805891/41103124-ebd6ccf6-6a57-11e8-8239-733abdd211e4.png)

..can't expect the OS to protect users from specific attacks.

..allowing the  "filename" parameter to be abused is the issue.

..abusing this locally as an unpriv user with elevated privs under win32 is probably not good. 

....probably spent to much time on this issue as there are more flaws.

**Comment by godsgood33** [comment]
Just committed a fix for this in the v1.3.3 branch.  If you pull that down and still see the issue, let me know if you have any suggested fixes.

**Comment by cyberperspectives** [comment]
Appears to be fixed.
