### ISSUE TITLE
Large eChecklist: MySQL server has gone away

### ISSUE THREAD

**Issue by cyberperspectives** [cyberperspectives/sagacity#4]
Ingesting an eChecklist with more than 7 or 8 hosts produces the following error, and the eChecklist fails to load any data.  We were able to delete host columns to 7 or less and get the eChecklist to import, so I think it's possibly a timeout issue, but we weren't able to successfully troubleshoot.

Also, instead of just printing the database error (which is often vague), we should also add a line with the query that bombed, since the code dynamically builds the queries.  It would make it easier to troubleshoot.

PHP Warning:  mysql::real_query():  Error reading results set's header in database.inc on line 280, followed by "MySQL server has gone away" message
Error reading result sets header in database.inc line 280

**Comment by godsgood33** [comment]
At this point, I am going to make the assumption that it is crashing because it is trying to add/update the findings from the file...there is no limiter that limits the amount of data it is trying to throw into the database at one time (approx line 340 of parse_excel_echecklist.php:

    if (!$db->add_Findings_By_Target($updated_findings, $new_findings)) {
        print "Error adding finding" . PHP_EOL;
    }

I've added a limiter so it will save after every 100 rows.  If the problem is not here, then we are going to have to dig further to figure out where the problem is because there are lots of queries here.

**Comment by JeffOdegard** [comment]
Fixed
