### ISSUE TITLE
database.inc 

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#51]
When loading two simultaneous Nessus scans, I get the following errors.

Illegal string offset 'id' in database.inc lines:
11069
11082
11086 ('os_id')
11101
11111
111123
111133
111140
111148
111156
111163
111166
111163
111166
111168

**Comment by godsgood33** [comment]
I'm going to need more to debug this.
1. Were you importing the same file twice, or two different file
2. The actual message sounds like an error in the XML parser because database.inc doesn't have 100k+ lines.  So unless you've got too many 1's in there, it's not likely a problem with database.inc or at least not all of it.
3. Only one indicated the os_id?  That line and the others around it are in the post_Processing method.  This is one thing that may have contributed to the excessive load time and auto-categorization in #52.

**Comment by JeffOdegard** [comment]
1.  It was two different nessus files.

2.  I think I added an extra one in the bug. I was transcribing from a
system I couldn't copy and paste from. I know I looked at those lines
myself in database. Inc

3. Yes, only one had os_id.  All of the lines were repeated at least 2 or 3
times.  I did a sort -u to reduce our down to transcribe.

**Comment by godsgood33** [comment]
Fixed
