### ISSUE TITLE
Enable xdebug in dev versions

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#56]
For the development versions only:

1. in php.ini, in the XDebug section, uncomment and configure:

```
zend_extension = "C:\xampp\php\ext\php_xdebug-2.6.1-7.2-vc15.dll"
xdebug.profiler_append = 0
xdebug.profiler_enable = 1
xdebug.profiler_enable_trigger = 0
xdebug.profiler_output_dir = "C:\xampp\tmp"
xdebug.profiler_output_name = "cachegrind.out.%t-%s"
xdebug.trace_output_dir = "C:\xampp\tmp"
```
2. in install.bat
Include the latest php_xdebug.dll file and copy it to C:\xampp\php\ext\
Get from  https://xdebug.org/files/php_xdebug-2.6.0-7.2-vc15.dll

3. also recommend that developers get a copy of QCacheGrindWin for performance analysis.
https://sourceforge.net/projects/qcachegrindwin/

None of this would be included in the production version.

**Comment by godsgood33** [comment]
My recommendation is duplicate the /conf/php.ini file and call it php-dev.ini.  Also put the dll file in the /conf folder.  Then in the install.bat file ask if this is a "development" installation.  If so, copy the dll to the appropriate directory and the php-dev.ini instead of the regular php.ini file.  This is going to be the cleanest way to do it.

Then I would just put in a note in the install suggesting they install QCacheGrindWin (providing a link if it is a dev install).

**Comment by JeffOdegard** [comment]
Fixed.
