### ISSUE TITLE
CVE Progress Bar "No NVD CVEs in Database"

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#6]
When the Sagacity starts downloading the CVEs, the CVE progress bar keeps going back to the "No NVD CVEs in Database" message, instead of staying on the "Downloading 2000 CVEs" or "Ingesting 2000 CVEs"  This makes it look like it's not working, and since it's slow, can cause the user to start troubleshooting or questioning whether the install is working.  

The progress should never return to the "No NVD CVE" message, but instead, increment the year being processed until complete.

**Comment by cyberperspectives** [comment]
This is more complicated that it looks.  Once you see it change back and forth a couple times, you get the drift of what it's doing.  Once it's starts ingesting it shouldn't reset to the "No NVD CVE..." message again.

Also, the confusing thing is that if I have it update the count so that it doesn't go change back to the "No NVD CVE..." it will remove the line altogether.  I would think this might be more confusing because they'll see the first year ingesting, then the whole line goes away, which might make them believe that it stopped, crashed, or done.  Thoughts?

**Comment by JeffOdegard** [comment]
Installation isn't interrupted anymore, and it seems to be working.
