### ISSUE TITLE
ST&E Ops Category Drop Down below bottom of page

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#69]
The ST&E Ops page Category Drop Down menu doesn't seem to be anchored to the menu icon, and many times, especially if there are a lot of categories on the page, will be below the bottom of the browser window, inaccessible.  This makes it impossible to access things like bulk edit, ckl export, etc.

**Comment by JeffOdegard** [comment]
Matt reports that this isn't an issue on a full size monitor and full screen Chrome window.  A laptop screen is where it shows up.

**Comment by JeffOdegard** [comment]
Is this something we can easily fix now?

**Comment by godsgood33** [comment]
Not really.  I need to know exact resolution for the window so I can duplicate, then figure out why it's doing it.  I'm using a 3rd party library to do it and it works every time I change my browser window size.

**Comment by JeffOdegard** [comment]
My laptop monitor is 1920x1080.  I loaded the Nessus vulnerability scan, then autocategorized and expanded all the categories.  I put my mouse over the first category menu icon, and this is what I saw.  You can just see the top of the menu at the bottom of the screen.  Putting my mouse over any of the other category icons, I can't see the menu at all.
![20190114_143041](https://user-images.githubusercontent.com/42775175/51142443-3d13f080-1809-11e9-9789-d7a0afd0a3cf.jpg)

This reproduces exactly what we are seeing on our laptops in the field.

**Comment by godsgood33** [comment]
That doesn't actually help.  My monitors are 1920 x 1080 too and they are fine.  "window" dimension are not the same as monitor resolution.  And since I can't replicate it, you're going to have to do some more investigative work to figure out what is going on.  Does it help if you clear your browser cache?  Is there an issue when the categories are collapsed?  The category your mouse is over is obviously not the top category, what does the top category show?  Do any of the other categories show correctly?

**Comment by JeffOdegard** [comment]
The category in the image is Novell SUSE, which is actually 3rd.  Before that is Uncategorized with 6 hosts and Centos with 1 host.  I emailed you a video.

**Comment by godsgood33** [comment]
See if the fix I just committed fixes it

**Comment by JeffOdegard** [comment]
Appears to be fixed.  Thanks!
